### ISSUE TITLE
Error on clicking available networks in nm-applet

### ISSUE THREAD

**Issue by compromyse** [vetu104/dwlb#2]
```(nm-applet:31791): Gtk-CRITICAL **: 20:39:48.681: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed```

This error occurs when I click on available networks in nm-applet..

**Comment by vetu104** [comment]
That comes from nm-applet though, not from the dwlbtray? Maybe it expects the gtk3/x11 style systray, where the app itself draws the item instead of the systray? That's not even possible in wayland. Trayitem itself seemed functional and I could swap networks with it though, the assertion might be harmless.

But ...

I noticed that submenus are not working correctly when testing this, the scrolling style makes them appear partly offscreen. Fixed that by changing the submenu style.

**Comment by compromyse** [comment]
Awesome! I'll test it..

**Comment by compromyse** [comment]
Great, it works now!
